In [13]:

with open('./datasets/TinyStories-train_cleaned.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [14]:
print("The length of the dataset in characters:", len(text))

The length of the dataset in characters: 1922009243


In [15]:
print(text[:1000])

One day, a little girl named Lily found a needle in her room. She knew it was difficult to play with it because it was sharp. Lily wanted to share the needle with her mom, so she could sew a button on her shirt.
Lily went to her mom and said, "Mom, I found this needle. Can you share it with me and sew my shirt?" Her mom smiled and said, "Yes, Lily, we can share the needle and fix your shirt."
Together, they shared the needle and sewed the button on Lily's shirt. It was not difficult for them because they were sharing and helping each other. After they finished, Lily thanked her mom for sharing the needle and fixing her shirt. They both felt happy because they had shared and worked together.
<|endoftext|>
Once upon a time, there was a little car named Beep. Beep loved to go fast and play in the sun. Beep was a healthy car because he always had good fuel. Good fuel made Beep happy and strong.
One day, Beep was driving in the park when he saw a big tree. The tree had many leaves that were

In [16]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print("The length of the dataset in characters:", vocab_size)
print("And the charaters are:",chars)


The length of the dataset in characters: 96
And the charaters are: ['\t', '\n', ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', '\\', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '|', '}', '~']


In [11]:
# import string
#
# allowed_chars = set(string.ascii_letters + string.digits + string.punctuation + '\n\t' + ' ')
#
# cleaned_text = ''.join([ch for ch in text if ch in allowed_chars])
#
# # verify the new vocab
# chars_cleaned = sorted(list(set(cleaned_text)))
# vocab_size_cleaned = len(chars_cleaned)
# print(vocab_size_cleaned)
# print(chars_cleaned)

96
['\t', '\n', ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', '\\', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '|', '}', '~']


In [12]:
# with open('./datasets/TinyStories-train_cleaned.txt', 'w', encoding='utf-8') as f:
#     f.write(cleaned_text)
#
# print("The length of the dataset in characters:", len(cleaned_text))
# print(vocab_size_cleaned)
# print(chars_cleaned)

The length of the dataset in characters: 1922009243
96
['\t', '\n', ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', '\\', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '|', '}', '~']


In [17]:
#Tokerizer:

stoi = {ch:i for i,ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}


encode = lambda s: [stoi[ch] for ch in s]
decode = lambda i: ''.join([itos[item] for item in i])

print(stoi['r'])
print(itos[stoi['r']])

print(encode("hello world"))
print(decode(encode("hello world")))

83
r
[73, 70, 77, 77, 80, 2, 88, 80, 83, 77, 69]
hello world


In [8]:
# we can also use tokenizers from Google sentence piece or tiktoken from openAi GPT
# !pip install tiktoken

# import tiktoken
#
# enc = tiktoken.get_encoding("gpt2")
# print(enc.n_vocab)
# print(enc.encode("hello world"))
# print(enc.decode(enc.encode("hello world")))
#
#
# # To get the tokeniser corresponding to a specific model in the OpenAI API:
# enc = tiktoken.encoding_for_model("gpt-4o")
#
#
# sample_encoding = enc.encode(text[:1000])
#
# print(sample_encoding)

50257
[31373, 995]
hello world


ValueError: Encountered text corresponding to disallowed special token '<|endoftext|>'.
If you want this text to be encoded as a special token, pass it to `allowed_special`, e.g. `allowed_special={'<|endoftext|>', ...}`.
If you want this text to be encoded as normal text, disable the check for this token by passing `disallowed_special=(enc.special_tokens_set - {'<|endoftext|>'})`.
To disable this check for all special tokens, pass `disallowed_special=()`.


In [19]:
#getting back to our encoding

import torch

# chunk_size = 1000000
#
# encoded_chunks = []
#
#
# for i in range(0, len(text), chunk_size):
#     chunk =

import os

data_path = './datasets/data_encoded.pt'

if os.path.exists(data_path):
    print("Loading cached tensor from disk...")
    data = torch.load(data_path)
else:
    print("Encoding text (first time — will be cached)...")
    data = torch.tensor(encode(text), dtype=torch.long)
    torch.save(data, data_path)
    print(f"Saved to {data_path}")

print(data.shape, data.dtype)
print(data[:1000])

Encoding text (first time — will be cached)...
Saved to ./datasets/data_encoded.pt
torch.Size([1922009243]) torch.int64
tensor([49, 79, 70,  2, 69, 66, 90, 14,  2, 66,  2, 77, 74, 85, 85, 77, 70,  2,
        72, 74, 83, 77,  2, 79, 66, 78, 70, 69,  2, 46, 74, 77, 90,  2, 71, 80,
        86, 79, 69,  2, 66,  2, 79, 70, 70, 69, 77, 70,  2, 74, 79,  2, 73, 70,
        83,  2, 83, 80, 80, 78, 16,  2, 53, 73, 70,  2, 76, 79, 70, 88,  2, 74,
        85,  2, 88, 66, 84,  2, 69, 74, 71, 71, 74, 68, 86, 77, 85,  2, 85, 80,
         2, 81, 77, 66, 90,  2, 88, 74, 85, 73,  2, 74, 85,  2, 67, 70, 68, 66,
        86, 84, 70,  2, 74, 85,  2, 88, 66, 84,  2, 84, 73, 66, 83, 81, 16,  2,
        46, 74, 77, 90,  2, 88, 66, 79, 85, 70, 69,  2, 85, 80,  2, 84, 73, 66,
        83, 70,  2, 85, 73, 70,  2, 79, 70, 70, 69, 77, 70,  2, 88, 74, 85, 73,
         2, 73, 70, 83,  2, 78, 80, 78, 14,  2, 84, 80,  2, 84, 73, 70,  2, 68,
        80, 86, 77, 69,  2, 84, 70, 88,  2, 66,  2, 67, 86, 85, 85, 80, 79,  2,


In [20]:
n = int(len(data) * 0.9)
train_data = data[:n]
test_data = data[n:]

In [22]:
batch_size = 4
block_size = 8

def get_batch(split):
    data = train_data if split == 'train' else test_data

    ix = torch.randint(len(data) - block_size, size=(batch_size,))
    print(ix)
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb,yb = get_batch('train')
print("inputs:")
print(xb.shape)
print(xb)
print("outputs:")
print(yb.shape)
print(yb)
print("====")

for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b, t]
        print(f"when input is {context.tolist()} and target is {target}")

tensor([1691943475,  802770190,  283862279,  382129314])
inputs:
torch.Size([4, 8])
tensor([[70, 77, 81, 14,  2, 67, 86, 85],
        [16,  2, 53, 73, 70,  2, 88, 66],
        [73, 66, 85,  2, 85, 73, 70,  2],
        [84, 66, 88,  2, 85, 73, 70,  2]])
outputs:
torch.Size([4, 8])
tensor([[77, 81, 14,  2, 67, 86, 85,  2],
        [ 2, 53, 73, 70,  2, 88, 66, 84],
        [66, 85,  2, 85, 73, 70,  2, 85],
        [66, 88,  2, 85, 73, 70,  2, 68]])
====
when input is [70] and target is 77
when input is [70, 77] and target is 81
when input is [70, 77, 81] and target is 14
when input is [70, 77, 81, 14] and target is 2
when input is [70, 77, 81, 14, 2] and target is 67
when input is [70, 77, 81, 14, 2, 67] and target is 86
when input is [70, 77, 81, 14, 2, 67, 86] and target is 85
when input is [70, 77, 81, 14, 2, 67, 86, 85] and target is 2
when input is [16] and target is 2
when input is [16, 2] and target is 53
when input is [16, 2, 53] and target is 73
when input is [16, 2, 53, 73] and 

In [36]:

import torch.nn as nn


class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)


    def forward(self, idx, targets=None):

        logits = self.token_embedding_table(idx)

        if targets is None:
            return logits, None

        B, T, C = logits.shape
        logits_flat = logits.view(B*T, C)
        targets_flat = targets.view(B*T)

        loss = nn.functional.cross_entropy(logits_flat, targets_flat)

        return logits, loss


    def generate(self, idx, max_len=50):
        for _ in range(max_len):
            logits, _ = self(idx)
            logits = logits[:-1:]
            probs = nn.functional.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)

        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)

print("The shape of the logits:", logits.shape)
print(loss)

The shape of the logits: torch.Size([4, 8, 96])
tensor(4.7951, grad_fn=<NllLossBackward0>)
