In [7]:

with open('./datasets/TinyStories-train_cleaned.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [8]:
print("The length of the dataset in characters:", len(text))

The length of the dataset in characters: 1922009243


In [9]:
print(text[:1000])

One day, a little girl named Lily found a needle in her room. She knew it was difficult to play with it because it was sharp. Lily wanted to share the needle with her mom, so she could sew a button on her shirt.
Lily went to her mom and said, "Mom, I found this needle. Can you share it with me and sew my shirt?" Her mom smiled and said, "Yes, Lily, we can share the needle and fix your shirt."
Together, they shared the needle and sewed the button on Lily's shirt. It was not difficult for them because they were sharing and helping each other. After they finished, Lily thanked her mom for sharing the needle and fixing her shirt. They both felt happy because they had shared and worked together.
<|endoftext|>
Once upon a time, there was a little car named Beep. Beep loved to go fast and play in the sun. Beep was a healthy car because he always had good fuel. Good fuel made Beep happy and strong.
One day, Beep was driving in the park when he saw a big tree. The tree had many leaves that were

In [2]:
# chars = sorted(list(set(text)))
# vocab_size = len(chars)
# print("The length of the dataset in characters:", vocab_size)
# print("And the charaters are:",chars)

vocab_size = 96
chars = ['\t', '\n', ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', '\\', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '|', '}', '~']

In [3]:
# import string
#
# allowed_chars = set(string.ascii_letters + string.digits + string.punctuation + '\n\t' + ' ')
#
# cleaned_text = ''.join([ch for ch in text if ch in allowed_chars])
#
# # verify the new vocab
# chars_cleaned = sorted(list(set(cleaned_text)))
# vocab_size_cleaned = len(chars_cleaned)
# print(vocab_size_cleaned)
# print(chars_cleaned)

In [4]:
# with open('./datasets/TinyStories-train_cleaned.txt', 'w', encoding='utf-8') as f:
#     f.write(cleaned_text)
#
# print("The length of the dataset in characters:", len(cleaned_text))
# print(vocab_size_cleaned)
# print(chars_cleaned)

In [5]:
#Tokerizer:

stoi = {ch:i for i,ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}


encode = lambda s: [stoi[ch] for ch in s]
decode = lambda i: ''.join([itos[item] for item in i])

print(stoi['r'])
print(itos[stoi['r']])

print(encode("hello world"))
print(decode(encode("hello world")))

83
r
[73, 70, 77, 77, 80, 2, 88, 80, 83, 77, 69]
hello world


In [6]:
# we can also use tokenizers from Google sentence piece or tiktoken from openAi GPT
# !pip install tiktoken

# import tiktoken
#
# enc = tiktoken.get_encoding("gpt2")
# print(enc.n_vocab)
# print(enc.encode("hello world"))
# print(enc.decode(enc.encode("hello world")))
#
#
# # To get the tokeniser corresponding to a specific model in the OpenAI API:
# enc = tiktoken.encoding_for_model("gpt-4o")
#
#
# sample_encoding = enc.encode(text[:1000])
#
# print(sample_encoding)

In [7]:
#getting back to our encoding

import torch

# chunk_size = 1000000
#
# encoded_chunks = []
#
#
# for i in range(0, len(text), chunk_size):
#     chunk =

import os

data_path = './datasets/data_encoded.pt'

if os.path.exists(data_path):
    print("Loading cached tensor from disk...")
    data = torch.load(data_path)
else:
    print("Encoding text (first time — will be cached)...")
    data = torch.tensor(encode(text), dtype=torch.long)
    torch.save(data, data_path)
    print(f"Saved to {data_path}")

print(data.shape, data.dtype)
print(data[:1000])

Loading cached tensor from disk...
torch.Size([1922009243]) torch.int64
tensor([49, 79, 70,  2, 69, 66, 90, 14,  2, 66,  2, 77, 74, 85, 85, 77, 70,  2,
        72, 74, 83, 77,  2, 79, 66, 78, 70, 69,  2, 46, 74, 77, 90,  2, 71, 80,
        86, 79, 69,  2, 66,  2, 79, 70, 70, 69, 77, 70,  2, 74, 79,  2, 73, 70,
        83,  2, 83, 80, 80, 78, 16,  2, 53, 73, 70,  2, 76, 79, 70, 88,  2, 74,
        85,  2, 88, 66, 84,  2, 69, 74, 71, 71, 74, 68, 86, 77, 85,  2, 85, 80,
         2, 81, 77, 66, 90,  2, 88, 74, 85, 73,  2, 74, 85,  2, 67, 70, 68, 66,
        86, 84, 70,  2, 74, 85,  2, 88, 66, 84,  2, 84, 73, 66, 83, 81, 16,  2,
        46, 74, 77, 90,  2, 88, 66, 79, 85, 70, 69,  2, 85, 80,  2, 84, 73, 66,
        83, 70,  2, 85, 73, 70,  2, 79, 70, 70, 69, 77, 70,  2, 88, 74, 85, 73,
         2, 73, 70, 83,  2, 78, 80, 78, 14,  2, 84, 80,  2, 84, 73, 70,  2, 68,
        80, 86, 77, 69,  2, 84, 70, 88,  2, 66,  2, 67, 86, 85, 85, 80, 79,  2,
        80, 79,  2, 73, 70, 83,  2, 84, 73, 74, 

In [8]:
n = int(len(data) * 0.9)
train_data = data[:n]
test_data = data[n:]

In [9]:
batch_size = 4
block_size = 8

def get_batch(split):
    data = train_data if split == 'train' else test_data

    ix = torch.randint(len(data) - block_size, size=(batch_size,))

    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb,yb = get_batch('train')
print("inputs:")
print(xb.shape)
print(xb)
print("outputs:")
print(yb.shape)
print(yb)
print("====")

for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b, t]
        print(f"when input is {context.tolist()} and target is {target}")

inputs:
torch.Size([4, 8])
tensor([[ 2, 84, 80,  2, 68, 80, 80, 77],
        [79, 16,  2, 42, 70,  2, 67, 66],
        [71, 77, 70, 88,  2, 69, 80, 88],
        [71, 85, 70, 89, 85, 93, 32,  1]])
outputs:
torch.Size([4, 8])
tensor([[84, 80,  2, 68, 80, 80, 77, 14],
        [16,  2, 42, 70,  2, 67, 66, 83],
        [77, 70, 88,  2, 69, 80, 88, 79],
        [85, 70, 89, 85, 93, 32,  1,  1]])
====
when input is [2] and target is 84
when input is [2, 84] and target is 80
when input is [2, 84, 80] and target is 2
when input is [2, 84, 80, 2] and target is 68
when input is [2, 84, 80, 2, 68] and target is 80
when input is [2, 84, 80, 2, 68, 80] and target is 80
when input is [2, 84, 80, 2, 68, 80, 80] and target is 77
when input is [2, 84, 80, 2, 68, 80, 80, 77] and target is 14
when input is [79] and target is 16
when input is [79, 16] and target is 2
when input is [79, 16, 2] and target is 42
when input is [79, 16, 2, 42] and target is 70
when input is [79, 16, 2, 42, 70] and target is 2
w

In [10]:

import torch.nn as nn


class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)


    def forward(self, idx, targets=None):

        logits = self.token_embedding_table(idx)

        if targets is None:
            return logits, None

        B, T, C = logits.shape
        logits_flat = logits.view(B*T, C)
        targets_flat = targets.view(B*T)

        loss = nn.functional.cross_entropy(logits_flat, targets_flat)

        return logits, loss


    def generate(self, idx, max_len=50):
        for _ in range(max_len):
            logits, _ = self(idx)
            logits = logits[:,-1, :]
            probs = nn.functional.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)

        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)

print(logits[0][0])

print("The shape of the logits:", logits.shape)
print(loss)

tensor([ 1.5503e+00, -9.3623e-01, -1.1108e+00,  1.2997e+00, -4.0047e-01,
        -2.1481e+00,  9.9836e-02, -1.5626e+00, -2.1166e+00, -8.4643e-01,
         1.0277e+00,  2.0278e+00, -5.5648e-01, -3.0031e-01, -6.3888e-01,
         1.3329e+00,  1.3199e+00,  2.0209e+00, -6.9425e-01, -1.4610e+00,
         1.9246e-01, -1.0186e+00,  7.9481e-01, -9.5832e-01, -1.6184e+00,
         6.4442e-01, -1.3760e+00,  1.6279e+00,  2.7419e-01,  2.7686e-01,
        -2.8563e+00, -9.7572e-01, -9.8659e-01,  1.2221e+00,  3.8250e-01,
        -7.5171e-02, -9.3623e-01,  1.4445e-01,  8.7565e-01,  1.9165e+00,
        -1.5576e+00, -6.0152e-01, -5.8230e-04, -1.4700e+00,  1.6696e+00,
         5.5927e-01,  1.2604e+00,  8.8595e-01, -1.6455e+00,  1.1404e+00,
         1.2007e+00,  2.4146e-01, -1.0916e-01, -7.6885e-01,  6.0599e-01,
         1.9666e+00,  1.0057e-01,  5.8626e-01,  1.0045e+00, -3.7338e-01,
        -6.9366e-01,  9.2563e-04,  1.8189e+00,  3.1691e-01,  4.4317e-02,
        -4.6893e-01,  2.7486e-01,  1.4435e+00,  8.2

In [11]:
#sampling it!

start_idx = torch.zeros((1,1), dtype = torch.long) # start with 0,0,0 which is "/"

sample = m.generate(start_idx, max_len=50)[0].tolist()

print(decode(sample))

	7_6kZa=:}[7](%&w,_N	?<_MB
y(&_}+wZ.~6_oFZzpx|ps=@K


In [12]:
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [14]:
batch_size = 32
steps = range(10000)
for step in steps:

    xb, yb = get_batch('train')

    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

2.23103666305542


In [ ]:
print(decode(m.generate(idx = torch.zeros((1,1) , dtype=torch.long), max_len = 500)[0].tolist()))

In [29]:
#Attention model mathematical trick
#consider the following example:

# from torch import

B,T,C = 4,8,2
x = torch.randn(B,T,C)
# print(x)

xbow = torch.zeros(B,T,C) #bow -> bag of words its the first and most navie way of predicting next chr with averaging out
for b in range(B):
    for t in range(T):
        xprev = x[b, :t+1]
        xbow[b,t] = torch.mean(xprev, 0)


#TRICK:
# instead of going through two for loop we can do a matrix multiplication with trianaglar unit value matrix to get the same result and it more effecient with GPU
a = torch.tril(torch.ones(3,3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0, 10, (3,2)).float()
c = a @ b

# print(a)
# print(b)
# print(c)

#Apply on the example
wei = torch.tril(torch.ones(T,T))
wei = wei / torch.sum(wei, 1, keepdim=True)

xbow2 = wei @ x  # wei = (T,T) @ x (B,T,C)  but the torch will see that there is no batch in the wei so it will automatically create a B,T,T where T,T is copied B times and parallaly execute


print(torch.allclose(xbow, xbow2))


# Rewritting it in better way
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = torch.functional.softmax(wei, dim=-1)

True
